Update guarantee.html
chillhaze/hell_en-team_project pull request #11
Opened 2021-04-02 14:01 UTC by maksik2018

add guarantee section

2021-04-02 15:18 UTC, OleksandrSemak requested changes

2021-04-02 15:18 UTC, OleksandrSemak commented on src/partials/guarantee.html
> +      <p class="guarantee__text">
Как по мне, тег "p" тут лишний, так как и в самой лишке можно поместить текст. Но если в разметку ты будешь добавлять еще что-то, кроме текста (например заинлайнишь в будущем свг какое-то), то тогда норм

2021-04-02 15:18 UTC, OleksandrSemak commented on src/partials/guarantee.html
> +        деньги.<span class="guarantee__text-coloured">*</span>
Оставил сообщение в общем чате по поводу единого класса для спанов. Как командой решим, так тут и поступим

2021-04-02 16:48 UTC, maksik2018 commented on src/partials/guarantee.html
> +      <p class="guarantee__text">
исправил

2021-04-02 16:48 UTC, maksik2018 commented on src/partials/guarantee.html
> +        деньги.<span class="guarantee__text-coloured">*</span>
пока поставил accent-text-color

2021-04-02 18:04 UTC, OleksandrSemak submitted a review, later dismissed

2021-04-03 12:03 UTC, Baklaikin submitted a review, later dismissed

2021-04-03 15:36 UTC, chillhaze requested changes

2021-04-03 15:36 UTC, chillhaze commented on src/partials/guarantee.html
> +  <h2 class="guarantee__title">Мы гарантируем</h2>
H2 нужно обернуть в div classs=container. 
далее добавить div guarantee__list-wrapper которому потом ты задашь серый фон и он будет тянутся на всю ширину страницы. внутри div guarantee__list-wrapper опять добавить div classs=container и в него вложить guarantee__list.

2021-04-03 16:30 UTC, maksik2018 commented on src/partials/guarantee.html
> +  <h2 class="guarantee__title">Мы гарантируем</h2>
привет сделал

2021-04-03 17:39 UTC, chillhaze approved these changes

2021-04-03 17:39 UTC, merged