разметка footer
chillhaze/hell_en-team_project pull request #14
Opened 2021-04-02 16:42 UTC by AlexandrHavrylov

добавляет разметку footer

2021-04-02 18:56 UTC, OleksandrSemak requested changes

2021-04-02 18:56 UTC, OleksandrSemak commented on src/partials/footer.html
> +      <svg width="14" height="19">
Получается такая ситуация. Мы фиксим размеры 14х19 (это близко для версии мобилки - но я бы все же поставил 15х20, это ближе к макету будет), но в версии для планшета и десктопа размеры огонька другие (22х30). Короче, из-за этого, по идее, мы не можем инлайнить размеры этой иконки, так как размер придется задавать через стили в зависимости от версии (мобилка, планшет, десктоп).

P.S.:  Посмотрел у Марины (она делала Хедер), она так же поставила размеры 14х19. Но в хедере там реально такие размеры. Думаю в идее размеры иконки в хедере и футере должны быть одинаковые. Так что нормально будет оставить 14х19 для мобилки. Но, как я и писал выше, лучше размеры не инлайнить, а задавать через стили уже потом.

2021-04-02 18:56 UTC, OleksandrSemak commented on src/partials/footer.html
> +    <a class="logo" href="index.html"
Вроде путь должен быть чуть другой. Сначала нужно выйти из папки partials, а потом уже брать файл index.html
Типа вот так "../index.html"
Но это не точно)

2021-04-02 18:56 UTC, OleksandrSemak commented on src/partials/footer.html
> +  <div class="contacts">
Это не критично, конечно, но у меня секция как раз называется contacts. Оно в моей секции вообще не логично, чтоб секция называлась contacts, но по ТЗ она так называется, и по идее я буду названия классов под нее подстраивать. И в таком случае у нас с тобой будет пересечение по названиям классов. Если кратко, то мне нужно будет прописывать названия классов с приставкой "contacts".

Тут нужно пока взять немного паузы, я пообщаюсь с Мариной и тогда уже будет понятнее, как тут поступить. Отпишусь в личку тебе

2021-04-02 18:56 UTC, OleksandrSemak commented on src/partials/footer.html
> +        <svg width="30" height="29">
Я так понимаю, что это размеры иконки телефона. Это размеры для десктопа, у планшета (24х23) и мобилки (20х19) немного другие. Думаю тут надо поступить так же, как и с лого. Либо забить и сделать везде одинаковый размер)

2021-04-02 18:56 UTC, OleksandrSemak commented on src/partials/footer.html
> +        <a class="contacts__link" href="#"></a>
Тут по идее тоже свг внутри ссылки должна быть? Инсты

2021-04-02 18:56 UTC, OleksandrSemak commented on src/partials/footer.html
> +        <a class="contacts__link" target="_blank" href="tel:+38(000)0000000">
Таргет бланк же переводит с ссылки на новую вкладку. Думаю, в случае с тлф это не актуальная фича. Могу ошибаться. Но вообще не критично, так или иначе. Просто обратил внимание

2021-04-02 18:56 UTC, OleksandrSemak commented on src/partials/footer.html
> +    <span class="rights__text">@ Все права защищены, 2019</span>
Думаю тут лишний либо див, либо спан. Достаточно чего-то и одного. + символ собачки (@) делается ж через спец символы - https://www.toptal.com/designers/htmlarrows/symbols/

2021-04-02 19:13 UTC, AlexandrHavrylov commented on src/partials/footer.html
> +    <a class="logo" href="index.html"
по идеи оно ж компилит все в index.html и путь берется относительно файла index.html

2021-04-02 19:15 UTC, AlexandrHavrylov commented on src/partials/footer.html
> +        <svg width="30" height="29">
Пока убрал, надо будет обсдуить на созвоне

2021-04-02 19:15 UTC, AlexandrHavrylov commented on src/partials/footer.html
> +        <a class="contacts__link" href="#"></a>
Иконки социальных сетей вставляйте фоном

2021-04-02 19:16 UTC, AlexandrHavrylov commented on src/partials/footer.html
> +        <a class="contacts__link" href="#"></a>
В ТЗ

2021-04-02 19:16 UTC, AlexandrHavrylov commented on src/partials/footer.html
> +        <a class="contacts__link" target="_blank" href="tel:+38(000)0000000">
случайно не туда дал, пофиксил, переместил туда где будет инста

2021-04-02 19:19 UTC, AlexandrHavrylov commented on src/partials/footer.html
> +    <span class="rights__text">@ Все права защищены, 2019</span>
убрал спан

2021-04-02 19:23 UTC, AlexandrHavrylov commented on src/partials/footer.html
> +  <div class="contacts">
пофиксил footer__contacts

2021-04-02 19:41 UTC, OleksandrSemak commented on src/partials/footer.html
> +    <a class="logo" href="index.html"
Согласен

2021-04-02 19:41 UTC, OleksandrSemak commented on src/partials/footer.html
> +        <svg width="30" height="29">
Окей

2021-04-02 19:46 UTC, OleksandrSemak commented on src/partials/footer.html
> +        <a class="contacts__link" href="#"></a>
Уточним у ментора

2021-04-02 19:46 UTC, OleksandrSemak commented on src/partials/footer.html
> +        <a class="contacts__link" target="_blank" href="tel:+38(000)0000000">
Гуд

2021-04-02 19:57 UTC, OleksandrSemak requested changes

2021-04-02 19:57 UTC, OleksandrSemak commented on src/partials/footer.html
> +  <div class="footer__contacts">
У нас сейчас нет блока "footer" по БЭМу, поэтому мы не можем выделить элемент "footer__contacts". Го просто класс "main-footer" - это будет блок, от которого уже пойдут элементы. Это предложение, может что-то другое придумаешь

2021-04-02 19:57 UTC, OleksandrSemak commented on src/partials/footer.html
> +      <svg width="14" height="19">
Решим на звонке

2021-04-02 19:57 UTC, OleksandrSemak commented on src/partials/footer.html
> +  <div class="rights">&#64; Все права защищены, 2019</div>
Сейчас вспомнил, что див - это ж не семантическая разметка. Может го вместо дива сделаем абзац (р)? Просто будет стоять абзац да и все (без дивов и спанов), он сам по себе ж тоже блочный, удобно. Но так хотяб семантически будет

2021-04-03 09:39 UTC, AlexandrHavrylov commented on src/partials/footer.html
> +  <div class="footer__contacts">
добавил тег footer с классом footer + сделал модификатором contacts--footer

2021-04-03 09:39 UTC, AlexandrHavrylov commented on src/partials/footer.html
> +  <div class="rights">&#64; Все права защищены, 2019</div>
fixed

2021-04-03 10:16 UTC, closed without merging