feature/contacts
chillhaze/hell_en-team_project pull request #19
Opened 2021-04-03 15:22 UTC by OleksandrSemak

Add full layout

2021-04-03 15:23 UTC, AlexandrHavrylov approved these changes

2021-04-03 16:26 UTC, chillhaze commented on src/partials/contacts.html
> +<section class="contacts">
div class=container и все его содержимое нужно поместить в div "обертка". в будущем этой обертке ты задашь background image, который будет тянутся на всю ширину страницы, за пределы контейнера.

2021-04-03 16:30 UTC, chillhaze requested changes

2021-04-03 16:30 UTC, chillhaze commented on src/partials/contacts.html
> +  <div class="container">
div class=container и все его содержимое нужно поместить в div "обертка". в будущем этой обертке ты задашь background image, который будет тянутся на всю ширину страницы, за пределы контейнера.

2021-04-03 18:48 UTC, OleksandrSemak commented on src/partials/contacts.html
> +  <div class="container">
У меня для этой цели как раз секция (contacts), которой я дам background-image. Картинка так же будет тянуться на всю ширину. В моем случае wrapper будет лишним

2021-04-04 14:55 UTC, chillhaze approved these changes

2021-04-04 14:55 UTC, chillhaze commented on src/partials/contacts.html
> +  <div class="container">
Согласен с твоим решением!

2021-04-04 14:55 UTC, merged