feature/contacts-styles
chillhaze/hell_en-team_project pull request #20
Opened 2021-04-03 15:23 UTC by OleksandrSemak

Add full styles

2021-04-03 15:24 UTC, AlexandrHavrylov approved these changes, later dismissed

2021-04-03 18:00 UTC, chillhaze requested changes

2021-04-03 18:00 UTC, chillhaze commented on src/sass/_contacts.scss
> +.container {
стили контейнера обновил, можно удалять

2021-04-03 18:52 UTC, OleksandrSemak commented on src/sass/_contacts.scss
> +.container {
Убрал стили

2021-04-04 14:55 UTC, chillhaze approved these changes

2021-04-04 14:55 UTC, merged