hero section
chillhaze/hell_en-team_project pull request #24
Opened 2021-04-03 18:14 UTC by Baklaikin

загрузил и оптимизировал png картинки, сделал все стили и разметку

2021-04-03 18:16 UTC, Baklaikin commented
Мне не все картинки подходят, которые Яна сделала, если можно, предлагая оставить свои. Фото училки во всех версиях в формате png

2021-04-03 18:40 UTC, chillhaze requested changes

2021-04-03 18:40 UTC, chillhaze commented on src/partials/hero.html
> +    <div class="container hero__container">
hero__container = container--hero

модификацию задаём именно классу контейнер, поэтому и модификатор будет у класса него, а не у hero, тем более они в одном теге указаны. это не большая/критическая ошибка, но так легче ориентироваться в коде. 
тоже и с hero__btn. тк btn - это отдельный элемент, который используется по всей странице и получает модификации в зависимости от секции где он расположен, то логический вид - это class="btn btn--hero"

2021-04-03 18:40 UTC, chillhaze commented on src/sass/_hero.scss
> +.hero {
все стили  - это отдельная ветка feture/hero-styles, нужно разделить, как договаривались

2021-04-04 09:20 UTC, Baklaikin commented on src/partials/hero.html
> +    <div class="container hero__container">
Саша, я там сделал не модификатор, а микс, который изменяет геометрию. Я в конспекте подсмотрел "В таких ситуациях используются миксы. Имя класса состоит из имён блока родителя и блока потомка по схеме родитель__потомок. Сделаем блок logo элементом блока page-header, добавив еще один класс-микс page-header__logo.

"

2021-04-04 14:59 UTC, chillhaze commented on src/partials/hero.html
> +    <div class="container hero__container">
не критично, главное не запутаться)

2021-04-04 15:00 UTC, chillhaze approved these changes, later dismissed

2021-04-04 15:05 UTC, chillhaze approved these changes

2021-04-04 15:56 UTC, closed without merging