feature/header
chillhaze/hell_en-team_project pull request #26
Opened 2021-04-03 22:25 UTC by MarynaMuntian

update header for tablet and desktop

2021-04-04 10:20 UTC, Baklaikin reviewed
Прошу добавить тип к кнопке type="button

2021-04-04 15:09 UTC, chillhaze requested changes

2021-04-04 15:09 UTC, chillhaze commented on src/partials/header.html
> +  <button>Консультация по телефону</button>
@Baklaikin : Прошу добавить тип к кнопке type="button

2021-04-05 08:08 UTC, MarynaMuntian commented on src/partials/header.html
> +  <button>Консультация по телефону</button>
Добавила

2021-04-05 10:54 UTC, chillhaze submitted a review, later dismissed

2021-04-05 10:57 UTC, merged