разметки и стили футтера
chillhaze/hell_en-team_project pull request #27
Opened 2021-04-04 10:55 UTC by AlexandrHavrylov

2021-04-04 12:10 UTC, OleksandrSemak requested changes

2021-04-04 12:10 UTC, AleksAlek commented on src/sass/_footer.scss
> +  @media screen and (max-width: 768px) {
Тут нужно ограничиться шириной в 767рх, иначе на 768-ом пикселе получается двойной отступ.

2021-04-04 12:10 UTC, AleksAlek commented on src/sass/_footer.scss
> +    margin-bottom: 30px;
Нужно убрать марджин в 30рх у второго элемента (на мобиле), так как сейчас получается, что лишка пробивает своего родителя и делает отступ, а надо, чтоб сам список сделал отступ.

P.S.: Список на мобиле тоже не должен давать никаких отступов, так как отступы в футере (где белый фон, без копирайта) должны быть сделаны паддингами (верхним и нижним) в 30рх. Это же будет работать и для десктопа и планшета, но там чуть другие размеры паддингов.

2021-04-04 12:10 UTC, AleksAlek commented on src/sass/_footer.scss
> +    content: ' ';
А разве нужен пробел в content? Мне казалось, что он должен быть пустой

P.S.: да, должен быть пустой

2021-04-04 12:10 UTC, AleksAlek commented on src/index.html
>  <html lang="ru">
Тут просто отступы поменялись?

2021-04-04 12:10 UTC, AleksAlek commented on src/partials/footer.html
> +    <div class="container"><p class="rights__text">&#64; Все права защищены, 2019</p></div>
По-моему див с классом container тут лишний. Эту часть можно просто поместить в общий контейнер для секции. + дополнительный див с классом container странно дает отступы, не так, как общий контейнер. Короче предлагаю это убрать и поместить копирайтс в общий див container, который есть в секции

P.S.: это как раз должно решить вопрос с тем, что на планшете не корректно расположены элементы по левому краю (копирайтс чуть дальше выпирает).

2021-04-04 12:10 UTC, AleksAlek commented on src/sass/_footer.scss
> +.logo--footer {
Ссылку нужно сделать инлайн-блок (сейчас она инлайн), иначе она некорректно отображается

2021-04-04 12:10 UTC, AleksAlek commented on src/sass/_footer.scss
> +  display: flex;
Для мобилы не хватает отступа в 4рх. Или можно сделать 5рх, так как на десктопе и планшете 5рх.

2021-04-04 12:10 UTC, AleksAlek commented on src/sass/_footer.scss
> +  margin-top: 20px;
У тебя вроде везде идут отступы сверху вниз, а тут наоборот. Чтоб было одинаково, лучше дать отступ нижний на ссылку (она как раз будет инлайн-блок).

2021-04-04 12:10 UTC, OleksandrSemak commented on src/partials/footer.html
> +          <a class="footer-contacts__link footer-contacts__link--phone" href="tel:+38(000)0000000">
Прописан класс footer-contacts__link, но никак не применён. На него как раз было бы неплохо дать дисплей инлайн-блок. Для первой ссылки, где используется класс, это бесполезно (тк там флекс), а вот для второй нужно, так как там инлайн (из-за чего ссылка некорректно отображается).

2021-04-04 12:10 UTC, OleksandrSemak commented on src/sass/_footer.scss
> +    &::after {
В общем из-за этого афтер получается такая штука - между двумя ссылками (телефоном и инстой) нет зазора, где бы ссылки не было. Без этого получается можно легко мискликнуть. Надо бы разделить их между собой. И тут, как по мне, афтер только мешает. Я бы вставил вертикальную черточку через инлайн свг и дал бы ей горизонтальные марджины. Так две ссылки будут наверняка разделены.

2021-04-04 12:10 UTC, OleksandrSemak commented on src/sass/_footer.scss
> +  padding-top: 30px;
Размер паддинга меняется в зависимости от версии. На мобилке 30, а на других - чуть больше

2021-04-04 15:18 UTC, chillhaze requested changes

2021-04-04 15:18 UTC, chillhaze commented on src/index.html
> -    <meta http-equiv="X-UA-Compatible" content="IE=edge">
тут не нужно добавлять"/", код взят из тех-задания

2021-04-04 15:18 UTC, chillhaze commented on src/index.html
> -    <link rel="preconnect" href="https://fonts.gstatic.com">
произошло дублирование ссылок шрифтов, возможно настройка в vs code какая-то особенная.
разметка Html и стили - это две разные ветки. обрати внимание на комменты от @OleksandrSemak

2021-04-05 18:21 UTC, AlexandrHavrylov commented on src/index.html
> -    <meta http-equiv="X-UA-Compatible" content="IE=edge">
VS Code автоматом добавляет, не могу убрать, руками можно тут удалить?

2021-04-05 18:21 UTC, AlexandrHavrylov commented on src/index.html
>  <html lang="ru">
VS Code что то сам себе меняет...

2021-04-05 18:38 UTC, AlexandrHavrylov commented on src/sass/_footer.scss
> +  padding-top: 30px;
fix

2021-04-05 18:46 UTC, AlexandrHavrylov commented on src/sass/_footer.scss
> +.logo--footer {
fix

2021-04-05 19:20 UTC, closed without merging