Feature/problems
chillhaze/hell_en-team_project pull request #7
Opened 2021-04-02 11:06 UTC by maksik2018

add section problems

2021-04-02 15:06 UTC, OleksandrSemak requested changes

2021-04-02 15:06 UTC, AleksAlek commented on src/partials/problems.html
> +    <span class="problems__title-coloured">помогаем</span> решить
Оставил сообщение в общем чате по поводу единого класса для спанов. Как командой решим, так тут и поступим

2021-04-02 15:06 UTC, OleksandrSemak commented on src/partials/problems.html
> +      <p class="problems__text">Название грамматики</p>
Как по мне, тег "p" тут лишний, так как и в самой лишке можно поместить текст. Но если в разметку ты будешь добавлять еще что-то, кроме текста (например заинлайнишь в будущем свг какое-то), то тогда норм

2021-04-02 16:20 UTC, maksik2018 commented on src/partials/problems.html
> +    <span class="problems__title-coloured">помогаем</span> решить
пока исправил как ты предложил, если не примет большинство верну

2021-04-02 16:21 UTC, maksik2018 commented on src/partials/problems.html
> +      <p class="problems__text">Название грамматики</p>
тег "p" удалил

2021-04-02 18:17 UTC, OleksandrSemak approved these changes

2021-04-02 18:17 UTC, OleksandrSemak commented on src/partials/problems.html
> +  <ol class="problems__list">
У нас для ol не обнулены стили. Это не критично, но лучше или 1) добавить тег ol в файл _common.scss, или 2) поменять ol на ul в разметке, или 3) при стилизации ещё раз задать обнуляющие стили точечно на этот список.

2021-04-02 18:17 UTC, OleksandrSemak commented on src/partials/problems.html
> +  <ol class="problems__list">
Увидел, что уже пофиксил

2021-04-02 18:17 UTC, OleksandrSemak commented on src/partials/problems.html
> +    <span class="problems__title-coloured">помогаем</span> решить
Окей

2021-04-03 14:46 UTC, chillhaze approved these changes

2021-04-03 14:47 UTC, merged