feature/contacts
chillhaze/hell_en-team_project pull request #8
Opened 2021-04-02 11:07 UTC by OleksandrSemak

add layout to contacts section

2021-04-02 14:27 UTC, maksik2018 submitted a review, later dismissed

2021-04-03 11:26 UTC, AlexandrHavrylov commented on src/sass/_contacts.scss
> +  min-width: 320px;
добавь max-width 480 px

2021-04-03 11:26 UTC, AlexandrHavrylov commented on src/sass/_contacts.scss
> +  width: 240px;
Имхо лишнее, ширина будет ограничиватся размером контейнера

2021-04-03 12:07 UTC, OleksandrSemak commented on src/sass/_contacts.scss
> +  width: 240px;
Если убрать фикс ширины, то текст полезет и не будет выглядеть, как на макете

2021-04-03 12:09 UTC, OleksandrSemak commented on src/sass/_contacts.scss
> +  min-width: 320px;
Добавил

2021-04-03 14:05 UTC, AlexandrHavrylov requested changes

2021-04-03 14:05 UTC, AlexandrHavrylov commented on src/partials/contacts.html
> +        <p class="contacts__label-text">Имя*</p>
Судя по макету это не текст а placeholder

2021-04-03 14:05 UTC, AlexandrHavrylov commented on src/partials/contacts.html
> +        <p class="contacts__label-text">Телефон*</p>
Судя по макету это не текст а placeholder

2021-04-03 14:05 UTC, AlexandrHavrylov commented on src/sass/_contacts.scss
> +  display: inline-flex;
просто display block/inline-block и они будут распологатся друг под другом остальные стили для флекса можно удалить

2021-04-03 14:05 UTC, AlexandrHavrylov commented on src/partials/contacts.html
> +      свяжется консультант и ответит на вопросы
Я бы сделал так, что бы избавить от фиксированной ширины на тексте. По макету логично везде переносится текст на этом месте.
" Оставь заявку на участие в <span class="accent-text-color">бесплатном занятии.</span> **< br >** С вами
      свяжется консультант и ответит на вопросы"

2021-04-03 14:07 UTC, OleksandrSemak commented on src/partials/contacts.html
> +      свяжется консультант и ответит на вопросы
Согласен

2021-04-03 14:07 UTC, OleksandrSemak commented on src/sass/_contacts.scss
> +  display: inline-flex;
Согласен

2021-04-03 14:10 UTC, OleksandrSemak commented on src/partials/contacts.html
> +        <p class="contacts__label-text">Телефон*</p>
Если сделаю это плейсхолдером, тогда подсказки не будет, так как плейсхолдер не выедет за пределы инпута. Можно сделать и текст, и плейсхолдер, но тогда одинаковый текст будет в двух разных местах. Зрительно выглядит, как на макете

2021-04-03 14:10 UTC, OleksandrSemak commented on src/partials/contacts.html
> +        <p class="contacts__label-text">Имя*</p>
Если сделаю это плейсхолдером, тогда подсказки не будет, так как плейсхолдер не выедет за пределы инпута. Можно сделать и текст, и плейсхолдер, но тогда одинаковый текст будет в двух разных местах. Зрительно выглядит, как на макете

2021-04-03 14:10 UTC, OleksandrSemak commented on src/sass/_contacts.scss
> +  width: 240px;
Решили вопрос, убрал

2021-04-03 14:19 UTC, AlexandrHavrylov approved these changes

2021-04-03 15:21 UTC, closed without merging